### ISSUE TITLE
Dependency Conflicts

### ISSUE THREAD

**Issue by paul-brenner** [fatbobman/ModelActorX#1]
Thanks for this great package!

Maybe this is just a problem I need to sort out on my own, but Xcode is complaining that:
```
'modelactorx' dependency on 'https://github.com/apple/swift-syntax.git' conflicts with dependency on 'https://github.com/swiftlang/swift-syntax' which has the same identity 'swift-syntax'. this will be escalated to an error in future versions of SwiftPM.
```
because I am using another package (swift-case-paths) which depends on
`.package(url: "https://github.com/swiftlang/swift-syntax", "509.0.0"..<"601.0.0-prerelease")`
while ModelActorX depends on
`.package(url: "https://github.com/apple/swift-syntax.git", from: "600.0.0")`

But it looks like https://github.com/apple/swift-syntax.git just redirects to https://github.com/swiftlang/swift-syntax so I have no idea which is the preferred approach.

**Comment by fatbobman** [comment]
@paul-brenner  you can fork a new branch and change version number

**Comment by paul-brenner** [comment]
Thanks, I had never tried that before. Works great!
